### ISSUE TITLE
Secure email endpoints other than @nhs.net

### ISSUE THREAD

**Issue by tonyyates** [iuec/current-spec-issues#3]
NHSmail is one of a number of Government secure email systems.  NHSmail connects securely to other Government secure email systems which allows users to share information confidently with their users.

The full list of secure Government email systems are below. They have email addresses ending:
.cjsm.net (Criminal and Justice)
.gcsx.gov.uk (Local Government/Social Services)
.gse.gov.uk (Central Government)
.gsi.gov.uk (Central Government including Department of Health)
.gsx.gov.uk (Central Government)
.hscic.gov.uk (The Health and Social Care Information Centre)
.mod.uk (Military)
.nhs.net (NHSmail)
.pnn.police.uk (Police)
.scn.gov.uk (Criminal and Justice)

Where **some** of these services are profiled on the DOS, information about a IUEC encounter may need to be permitted to send.

A single instance has been noted around the need to send information to .cjsm.net

**Comment by mattstibbs** [comment]
@tonyyates are you happy to update the guidance in the tech-standards repo?

**Comment by tonyyates** [comment]
Yes

**Comment by paul-jefferies** [comment]
@tonyyates We have also had customers requesting the ability to send to services profiled on the DOS using .cjsm.net email addresses too. So we are keen to see the guidance updated for this issue soon as well.

**Comment by mattstibbs** [comment]
This has been updated in the tech standards on branch develop
